{
 "title": "plausible-exporter",
 "description": "Demo dashboard for plausible-exporter",
 "tags": [
  "plausible",
  "analytics",
  "website"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(plausible_visitors, site_id)"
    }
   },
   { "name": "prom", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Useful links",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "![](https://icons.duckduckgo.com/ip3/riesinger.dev.ico)  [riesinger.dev](https://riesinger.dev?utm_source=plausible-exporter-grafana)\n\n![](https://icons.duckduckgo.com/ip3/plausible.io.ico) [Plausible](https://plausible.io)\n\n![](https://icons.duckduckgo.com/ip3/github.com.ico) [plausible-exporter](https://github.com/riesinger/plausible-exporter)\n\n"
   }
  },
  {
   "title": "Visitors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "plausible_visitors{site_id=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Visit Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "plausible_visit_duration{site_id=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Page Views",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "plausible_pageviews{site_id=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bounce Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "plausible_bounce_rate{site_id=\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}