name: Binary
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          make static BIN=plausible-exporter-${{matrix.goos}}-${{matrix.goarch}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: plausible-exporter-${{ matrix.goos }}-${{ matrix.goarch }}
          path: plausible-exporter-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "./plausible-exporter-*"
